### ISSUE TITLE
재택 신청

### ISSUE THREAD

**Issue by gimhanul** [kosa-midas-3/bbabbico#8]
### ✨ Describe

user - 재택 근무 신청을 할 수 있어야 합니다.
admin - 재택 근무 신청을 수락 / 거절 할 수 있어야 합니다.

### ✅ Tasks

- [x] home apply entity
- [x] home apply repository
- [x] 재택 근무 신청
- [x] 신청 수락 / 거절
